version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - unused
    - staticcheck
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: var-naming
        disabled: true
output:
  show-stats: true
  sort-order:
    - file
    - linter
