name: "Go Coverage"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 10

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 'stable'
        cache: true

    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        coverage-threshold: 80
        cover-pkg: ./...
        ignore-pattern: |
          \.pb\.go$
          \_string\.go$
          loxxy/main\.go$
        report-url: ""

    - name: Update coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0

      # only update the badge when we merge into main
      if: github.ref_name == 'main'
      with:
        auth: ${{ secrets.COVERAGE_GIST_SECRET }}
        gistID: da44b047ba1e0c16c4f14224e28e2618
        filename: coverage.json
        label: Go Coverage
        message: ${{ steps.coverage.outputs.coverage-pct-1dp }}%
        color: ${{ steps.coverage.outputs.meets-threshold == 'true' && 'green' || 'red' }}

    - name: Generate coverage tree map
      run: |
        go run github.com/nikolaydubina/go-cover-treemap@latest \
          -coverprofile ${{ steps.coverage.outputs.gocov-agg-pathname }} \
          -only-folders=true > treemap.svg

    - name: Save Coverage Report & Treemap
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: go-coverage-results
        path: |
          ${{ steps.coverage.outputs.report-pathname }}
          treemap.svg
